### ISSUE TITLE
Haskell Bindings, and Apron Support Questions

### ISSUE THREAD

**Issue by sykora** [eth-sri/ELINA#21]
I'm in the process of writing Haskell bindings for ELINA, and having found Apron, I'm considering going through it instead for consistency.

What is the status of ELINA's Apron support? Is it a preferable way forward for implementing language bindings, or should I be binding ELINA directly?

Thanks!

**Comment by sykora** [comment]
Thanks. I'll close this ticket for now, since I've decided to bind ELINA directly. I'll create other tickets for more specific questions.

**Comment by martin-neuhaeusser** [comment]
Haskell bindings for a static analysis framework such as ELINA or apron would be great!
Is anybody aware of going activities in that direction?
