### ISSUE TITLE
Segmentation fault by minimize

### ISSUE THREAD

**Issue by skcho** [eth-sri/ELINA#23]
Hello,

The following code, in which it tries to minimize an abstract value, failed with segmentation fault.

```ocaml
open Apron

let _ =
  let man = Elina_poly.manager_alloc_loose () in
  let env = Environment.make [||] [||] in
  let abs = Abstract1.top man env in
  Abstract1.minimize man abs
```

```
segmentation fault: 11
```
Same result in C.

```c
#include <limits.h>
#include "ap_environment.h"
#include "ap_abstract1.h"
#include "opt_pk.h"

int main(int argc, char **argv){
  elina_manager_t* man = opt_pk_manager_alloc(false);
  ap_environment_t* env = ap_environment_alloc_empty();
  ap_abstract1_t abs = ap_abstract1_top(man, env);
  ap_abstract1_minimize(man, &abs);
  return 0;
}
```

I am suspecting there may be a type mismatch on [registering the minimize function](https://github.com/eth-sri/ELINA/blob/a67a647f7a549dcbc68955cd10ac74a09e446d40/elina_poly/opt_pk_internal.c#L207). The type of its argument is `opt_pk_t*`, not `opt_pk_array_t*`, though I am not sure this is the source of the crash.

```c
void opt_pk_minimize(elina_manager_t* man, opt_pk_t* o);
```

**Comment by GgnDpSngh** [comment]
Hi,

The minimize function is just there as a placeholder. It is not supported by ELINA. Does your analysis depend critically on it?

Cheers,
Gagan

**Comment by skcho** [comment]
OK, I understand. 😄 

> What do you need it for?

I used Apron's octagon domain into our analyzer, at that time I needed the minimize function to keep small size of abstract states. Then, I simply changed the manager to Elina's, which triggered the issue.

> the conversion algorithm already removes all redundant constraints/generators

If it already does the minimizations in another place, what about using a void function as the replaceholder, in order to avoid the segmentation faults. Of course, we can change our analyzer not to call the function when using Elina's domain. 😉 

Sincerely,
Sungkeun

**Comment by skcho** [comment]
Yes, you're right. What I have used is `minimize_environment`, which may not invoke the `minimize` function. I wrongly thought they are related... (I am sorry for that) and coincidently I succeeded to make the test case. 😓 

Anyway, thank you for the fix!
Sungkeun
