### ISSUE TITLE
Segfault when assigning to a projected, added dimension using a linexpr. 

### ISSUE THREAD

**Issue by sykora** [eth-sri/ELINA#38]
I seem to have arrived at a rather specific corner-case of assignment-related segfaults:

```c
#include "elina_linexpr0.h"
#include "opt_pk.h"
#include "opt_pk.h"

int main() {
  char* dim_names[] = { "x" };
  elina_manager_t* m = opt_pk_manager_alloc(false);

  opt_pk_array_t* p = opt_pk_top(m, 0, 0);

  elina_dimchange_t* dc = elina_dimchange_alloc(1, 0);
  dc->dim[0] = 1;
  opt_pk_add_dimensions(m, true, p, dc, true);

  elina_linexpr0_t* e = elina_linexpr0_alloc(ELINA_LINEXPR_SPARSE, 0);
  elina_linexpr0_set_cst_scalar_int(e, 23);

  elina_dim_t adim = 0;

  opt_pk_assign_linexpr_array(m, true, p, &adim, &e, 1, NULL);

  elina_lincons0_array_t lca = opt_pk_to_lincons_array(m, p);
  elina_lincons0_array_print(&lca, dim_names);

  elina_dimchange_free(dc);
  elina_lincons0_array_clear(&lca);
  elina_linexpr0_free(e);
  opt_pk_free(m, p);
  elina_manager_free(m);
}
```
The following rather specific conditions need to be true to trigger the segfault:

1. The dimension must have been added after creating the polyhedron (e.g. a polyhedron created as `top` initially with the dimension intact, and subsequently projected does not trigger the segfault).
2. The dimension must be projected (e.g. an unconstrained dimension does not trigger this segfault).
3. The assignment must be performed with a `linexpr` (e.g. using a `texpr` does not trigger this segfault).

It is possible that I have yet again neglected to initialize an important data structure, do let me know if that is the case.

**Comment by sykora** [comment]
Changing it to `dc->dim[0] = 0` does not seem to mitigate the segfault.

**Comment by GgnDpSngh** [comment]
Thanks for this feedback. I fixed the problem, it should work now.

Cheers,
Gagan

**Comment by sykora** [comment]
Excellent, thank you!
