### ISSUE TITLE
Parallel assignment outputs top in the octagon domain.

### ISSUE THREAD

**Issue by gavlegoat** [eth-sri/ELINA#41]
In the octagon domain, performing a parallel assignment yields top even when the assignment operation is identity. There is example code showing this behavior [here](https://gist.github.com/gavlegoat/5d89bed2678893c82308096c30ac262a).

**Comment by GgnDpSngh** [comment]
Hi there,

Thanks for pointing this out. This was indeed a subtle bug that we did not detect before. It has been fixed now. Let me know if you have any further issues.

Cheers,
Gagan
