### ISSUE TITLE
Unexpected behavior with Octagons

### ISSUE THREAD

**Issue by shankarapailoor** [eth-sri/ELINA#43]
Hi Gagandeep!

We are experiencing strange issues with Octagons when performing a series of affine transformations. At a high level, we first convert the octagon to linear constraints and then print it. After that, if we don't clear constraints, the transformations yield bot and if we do, we get a nonempty domain. We have repro'd the issue [here](https://github.com/shankarapailoor/elina-octagon) with more details in the README. When using other domains like boxes or zonotopes, we see consistent behavior. Any assistance would be appreciated. 

Regards,
Shankara

**Comment by GgnDpSngh** [comment]
Hi there,

Thanks for reporting this. We will look into this and let you know as soon as possible.

P.S.- The Octagon domain is not a good match for performing the affine transformation as it is not exact for this and can lose precision.

Cheers,
Gagan

**Comment by GgnDpSngh** [comment]
Hi there,

Thanks for your feedback and detailed bug report. It took me a while to figure out but I have managed to fix the bug and your code now produces the same result whether the array is cleared or not. Let me know if you have any other issues with ELINA.

Cheers,
Gagan
