### ISSUE TITLE
'sys/sysinfo.h' cannot be found on mac

### ISSUE THREAD

**Issue by caballa** [eth-sri/ELINA#45]
This is after commit https://github.com/eth-sri/ELINA/commit/28fc733877d561834af57b3ec7bab051afb296dd

```
In file included from zonoml_internal.c:30:
./zonoml_internal.h:36:10: fatal error: 'sys/sysinfo.h' file not found
#include <sys/sysinfo.h>
```

**Comment by GgnDpSngh** [comment]
Hi Jorge,

I made a fix by removing the dependency on 'sys/sysinfo.h'. Can you check if this fixes the issue on your mac?

Cheers,
Gagan

**Comment by caballa** [comment]
It works now.
Thanks again!
