### ISSUE TITLE
clang: error: unknown argument: '-mno-fused-madd'

### ISSUE THREAD

**Issue by caballa** [eth-sri/ELINA#51]
The error is with clang 

```
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
```

It's caused by the option `mno-fused-add` in `Makefile.config`:

```
# Architecture specific flags
AFLAGS = -D_GNU_SOURCE -pthread -fno-tree-vectorize -m64 -march=native -mno-fused-madd
````

**Comment by GgnDpSngh** [comment]
Hi Jorge,

I have replaced the -mno-fused-add flag with the ffp-contract flag which should work for clang, let me know if it works on your system.

Cheers,
Gagandeep Singh

**Comment by caballa** [comment]
It works.
Thanks!
