### ISSUE TITLE
Compilation failure due to wrong path

### ISSUE THREAD

**Issue by JacksonZyy** [eth-sri/ELINA#54]
Hi, 

I am installing ELINA as a dependency of the ERAN analyzer.
The make command gave me the following errors:
/usr/bin/ld: cannot find -lmpfr
/usr/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
Makefile:78: recipe for target 'libelinaux.so' failed
make[1]: *** [libelinaux.so] Error 1

I am running it on a compute cluster, so I don't have sudo rights.
I install m4, gmp, mpfr in my home dir instead of the default dir. Therefore I suppose the failure is due to path not being correctly set?
But I am confused about how to SET the path Correctly. Shall I change some environment variables? Or to run configure with certain options?
I would appreciate it if you could give me a precise answer. Thanks!

Regards,
Yuyi

**Comment by GgnDpSngh** [comment]
Hi Yuyi,

Thanks for your interest in using ELINA. You could try:

export LD_LIBRARY_PATH=$$LD_LIBRARY_PATH:path_to_libelinaux.so:path_to_libmpfr.so:path_to_libgmp.so

Let me know if it works.

best,
Gagandeep  Singh

**Comment by JacksonZyy** [comment]
> Hi Yuyi,
> 
> Thanks for your interest in using ELINA. You could try:
> 
> export LD_LIBRARY_PATH=$$LD_LIBRARY_PATH:path_to_libelinaux.so:path_to_libmpfr.so:path_to_libgmp.so
> 
> Let me know if it works.
> 
> best,
> Gagandeep Singh

**Comment by JacksonZyy** [comment]
Hi,

I tried to update the $LD_LIBRARY_PATH, but I am STILL SEEING the same error.
I echo the same path, it gave me:
:path_to_libelinaux.so:path_to_libmpfr.so:path_to_libgmp.so
Meaning the previous $LD_LIBRARY_PATH is empty, I don't know if it is correct.
Any further suggestions? Thanks!

Regards,
Yuyi

**Comment by GgnDpSngh** [comment]
Hi Yuyi,

Alternatively, you could change "rpath" by adding the flags "-Wl,-rpath=path_to_the_shared_object" in the Makefile.  See here:

https://en.wikipedia.org/wiki/Rpath

Let me know if it works.

best,

**Comment by JacksonZyy** [comment]
Hi, 

Sorry for the late reply. 
I finally chose to install the system on a server with sudo rights.
Thanks for the help so far.

Regards,
Yuyi
