### ISSUE TITLE
Wrong CDD_PREFIX after ./configure --cdd-prefix

### ISSUE THREAD

**Issue by rnbguy** [eth-sri/ELINA#77]
At these lines, `-I/usr/local/include/cddlib` assumes the location of `cddlib`.

https://github.com/eth-sri/ELINA/blob/2d1f00f1d3b2e0efbe36534991b22040b6eb7182/fppoly/Makefile#L36
https://github.com/eth-sri/ELINA/blob/2d1f00f1d3b2e0efbe36534991b22040b6eb7182/fppoly/Makefile#L39

So even if I set it through `./configure --cdd-prefix`, it does not include the correct location.

It should be `-I$(CDD_PREFIX)`.

**Comment by GgnDpSngh** [comment]
Hi Ranadeep,

Thanks for the feedback, I have updated the makefile, let me know if it works.

Cheers,
Gagandeep Singh

**Comment by rnbguy** [comment]
Hi Gagandeep, you missed out line 36.

https://github.com/eth-sri/ELINA/blob/0e4960ddda203ab3d1f78fa6c04a36e4d96d3b82/fppoly/Makefile#L36

**Comment by GgnDpSngh** [comment]
alright, I have fixed that as well. let me know if it works.

Cheers,
Gagandeep Singh

**Comment by rnbguy** [comment]
super. it works perfectly now :)

ps. if possible, please bump `gurobi90` to `gurobi91`. `ERAN`, `ELINA`, `DEEPG` compile fine with `gurobi91`.
