### ISSUE TITLE
OSError: libfppoly.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by WhoAmI-kai** [eth-sri/ELINA#80]
When I run `/ELINA/python_interface/fppoly_import`,  I get an error:
` OSError: libfppoly.so: cannot open shared object file: No such file or directory `.

I tried looking in directory `/usr/local/lib` and '/usr/lib' , and I also use the `find` command to find, but I can't find `libfppoly.so`

I think I may be missing this file, how can I solve this problem?

Thank you very much for your reply.

**Comment by GgnDpSngh** [comment]
Hi there,

Try going to ELINA/fppoly directory, then run make followed by make install. Let me know if it works.

Cheers,
Gagandeep Singh

**Comment by WhoAmI-kai** [comment]
When I run make in ELINA/fppoly directory, I get an error:
`cc: error: fppoly.o: no such file or directory`
`Makefile:60: recipe for target 'fppoly.o' failed`
`make: *** [fppoly.o] Error 1`

**Comment by WhoAmI-kai** [comment]
I have solved the above problems. The reason for the problem is the lack of `cddlib`.

**Comment by GgnDpSngh** [comment]
Awesome.

Cheers,
Gagandeep Singh
