### ISSUE TITLE
error: ‘AP_SCALAR_MPFR’ undeclared (first use in this function); did you mean ‘ELINA_SCALAR_MPFR’?

### ISSUE THREAD

**Issue by jsum007** [eth-sri/ELINA#83]
Hey, while trying to install ELINA on my system, I'm constantly facing this issue on compiling using make. With the error message as follows: 

make[1]: Entering directory '/home/sum/IRISA/ERAN/ELINA/elina_oct'
cc -c -Wcast-qual -Wswitch -Wall -Wextra -Wundef -Wcast-align -Wno-unused -U__STRICT_ANSI__ -fPIC -O3 -DNDEBUG -Werror-implicit-function-declaration -Wbad-function-cast -Wstrict-prototypes -Wno-strict-overflow -std=c99 -g  -DNUM_LONGLONGRAT -DNUM_DOUBLE -DTHRESHOLD=0.75 -DTIMING -D_GNU_SOURCE -pthread -fno-tree-vectorize -m64 -march=native -ffp-contract=off  -DVECTOR  -I../ -I../elina_auxiliary -I../elina_linearize -I../partitions_api   -o opt_oct_closure_comp_sparse.o opt_oct_closure_comp_sparse.c -L../partitions_api -lpartitions -L../elina_auxiliary -lelinaux -L../elina_linearize -lelinalinearize  -lmpfr  -lgmp -lm
In file included from opt_oct_hmat.h:31,
                 from opt_oct_closure_comp_sparse.h:28,
                 from opt_oct_closure_comp_sparse.c:22:
opt_oct_internal.h: In function ‘double_set_elina_scalar’:
opt_oct_internal.h:298:8: error: ‘AP_SCALAR_MPFR’ undeclared (first use in this function); did you mean ‘ELINA_SCALAR_MPFR’?
  298 |   case AP_SCALAR_MPFR:
      |        ^~~~~~~~~~~~~~
      |        ELINA_SCALAR_MPFR
opt_oct_internal.h:298:8: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [Makefile:67: opt_oct_closure_comp_sparse.o] Error 1
make[1]: Leaving directory '/home/sum/IRISA/ERAN/ELINA/elina_oct'
make: *** [Makefile:47: c] Error 2

Please help asap!! Thanks in anticipation!

**Comment by GgnDpSngh** [comment]
Hi there,

Thanks for the feedback, I pushed a fix, please pull and let me know if you encounter any other issues.

Cheers,
Gagandeep Singh

**Comment by jsum007** [comment]
Hi,
It's working now. Thanks a lot!
Regards, 
Sumit Jain
