### ISSUE TITLE
-march=native and -DTIMING not supported in Apple M1

### ISSUE THREAD

**Issue by caballa** [eth-sri/ELINA#90]
I get this error

```
clang: error: the clang compiler does not support '-march=native'
```

I found some discussion about it here:  https://stackoverflow.com/questions/65966969/why-does-march-native-not-work-on-apple-m1

**Comment by caballa** [comment]
I think the option `-DTIMING` also causes problems with Apple M1 because it generates assembly code.

**Comment by GgnDpSngh** [comment]
Hi Jorge,

Thanks for the feedback. I have disabled both flags for Mac, please let me know if it works!

Cheers,
Gagandeep Singh

**Comment by caballa** [comment]
it works. Thanks again!
